:-module(dragon_curve, [background_knowledge/2
                       ,metarules/2
                       ,initial_example/2
                       ,f/2
                       ,g/2
                       ,plus/2
                       ,minus/2
                       ,empty/2
                       ,generate_examples/5
                       ]).

:-use_module(project_root(configuration),[]).
:-use_module(lib(poker/poker_configuration),[]).
:-use_module(lib(poker/poker_auxiliaries)).

:-use_module(data(poker_examples/test_harness)).

:-use_module(l_systems_constraints).

/** <module> Learn an L-System grammar modelling the Dragon Curve fractal.

Work in Progress.

*/

% Language alphabet for the constraints defeined
% in grammar_constraints.pl
%
grammar_constraints:target(s).
grammar_constraints:invented(inv_1).
grammar_constraints:invented(inv_2).
grammar_constraints:preterminal(f).
grammar_constraints:preterminal(g).
grammar_constraints:preterminal(+).
grammar_constraints:preterminal(-).
grammar_constraints:preterminal(empty).

/*
% Raises error despite importing poker_auxiliaries. Why?
% Best way to use currently is to load file for the first time when this
% is commented out, then uncomment and reload the file (with make/0).

:-poker_auxiliaries:set_poker_configuration_option(clause_limit,[4]).
:-poker_auxiliaries:set_poker_configuration_option(gestalt,[true]).
:-poker_auxiliaries:set_poker_configuration_option(flatten_prove_all,[true]).
:-poker_auxiliaries:set_poker_configuration_option(max_invented,[1]).
:-poker_auxiliaries:set_poker_configuration_option(respecialise,[false]).
:-poker_auxiliaries:set_poker_configuration_option(unlabelled_examples,[200]).
:-poker_auxiliaries:set_poker_configuration_option(unlabelled_examples_order
						  ,[random]).
*/

%!	safe_example(-Example) is nondet.
%
%	Generate a safe scaffold for unlabelled examples.
%
%	For examples with list arguments, generating unlabelled examples
%	during learning can "go infinite". This predicate ensures that
%	list arguments in examples are limited in length.
%
%	This argument should not itself be a generator of ground
%	examples. This is left to the user to avoid.
%
poker_configuration:safe_example(m(s,Is,Os,[])):-
        K = 8
	,between(0,K,I)
	,length(Is,I)
	,between(0,K,J)
	,length(Os,J).


background_knowledge(s/3,[f/2
                         ,g/2
                         ,plus/2
                         ,minus/2
                         ,empty/2
                         ]).

metarules(s/3,[ls_base,ls_rec,ls_rec_2]).
%metarules(s/3,[ls_base,ls_rec]).

initial_example(s/3,E):-
	generate_initial(dragon_curve,4,0,4,Es)
        ,member(E,Es).

f --> [f].
g --> [g].
plus --> [+].
minus --> [-].
empty --> [].


% Generate examples for evaluation.
% Examples are generated by test harndes predicates.
%
generate_examples(pos,dragon_curve,all,0,14).
generate_examples(neg,not_dragon_curve,all,0,4).
